spring:
  application:
    name: code-smells
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5435/postgres}
    username: ${SPRING_DATASOURCE_USERNAME:smells_app}
    password: ${SPRING_DATASOURCE_PASSWORD:smells_app}
    hikari:
      maximum-pool-size: 8
      connection-timeout: 10000
    driver-class-name: org.postgresql.Driver
  thymeleaf:
    cache: false

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
    access:
      default: read_only